### ISSUE TITLE
You do not have a working installation of the service_identity module

### ISSUE THREAD

**Issue by Pen-Ace** [P0cL4bs/WiFi-Pumpkin-deprecated#444]
## What's the problem (or question)?

I am trying to get WFP working with Parrot OS 4.4 - VM

everything installs without issue, but when i fire it up i get this error:

You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 50, in <module>
    from Core.Main import Initialize
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 52, in <module>
    from Core.helpers.report import frm_ReportLogger
  File "/usr/share/WiFi-Pumpkin/Core/helpers/report.py", line 2, in <module>
    from PyQt4.QtWebKit import QWebView
ImportError: No module named QtWebKit

I have tried and installed evey dependency and service_identity module but still get the same error. I would appreciate any help to resolve this issue.
Thanks.

**Comment by Pen-Ace** [comment]
Closed without comment or help? @mh4x0f

**Comment by 101zombie101** [comment]
Same here. Have that problem running kali on my pi
